# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'School programm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for School programm
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase'


end
